### ISSUE TITLE
Is there a way to add an onClick event to a data point? 

### ISSUE THREAD

**Issue by darthzeran** [tannerlinsley/react-charts#106]
I mean is there a field where it can be added in without having to make a custom tooltip?

**Comment by darthzeran** [comment]
Bumping because I realized that I did still use the tooltip, and only through the tooltip could onCLick work

**Comment by tannerlinsley** [comment]
Due to a massive overhaul and rewrite of React Charts to TypeScript and a massively upgraded public API, this issue is being bulk closed for triage. The latest version can be tested via the `react-charts@beta` tag. Documentation is in the process of being upgraded, but thankfully, everything is fully typed now, so you can explore the API that way for now.

If, *after testing or playing with the v3 beta*, you believe your issue is still not addressed or relevant, feel free to open a new issue.
