### ISSUE TITLE
Support threshold line

### ISSUE THREAD

**Issue by EladBezalel** [tannerlinsley/react-charts#111]
It would be cool to have this functionality 
![image](https://user-images.githubusercontent.com/6004537/90321039-df003f80-df4e-11ea-838b-b1d178552d35.png)

![image](https://user-images.githubusercontent.com/6004537/90321024-c2fc9e00-df4e-11ea-9567-f555c0be951c.png)

**Comment by GavBaros** [comment]
@EladBezalel I searched everywhere for a react graph library that supports this. Have you come across a solution for your use case?

**Comment by EladBezalel** [comment]
I don't remember if I found a solution for it honestly..
Did you try visx?

**Comment by GavBaros** [comment]
Just glanced through the visx docs but found nothing related, maybe I have to dig deeper. I find this surprising how something so simple is missed by all the react chart libraries I've come across!

**Comment by GavBaros** [comment]
[React Stock Charts Interactive Y Coordinate](https://rrag.github.io/react-stockcharts/documentation.html#/interactive_y_coordinate) is the closest I could get to a threshold of sorts by the way if that can help anyone looking.

**Comment by GavBaros** [comment]
Actually this is best: http://recharts.org/en-US/examples/LineChartWithReferenceLines !

**Comment by tannerlinsley** [comment]
Due to a massive overhaul and rewrite of React Charts to TypeScript and a massively upgraded public API, this issue is being bulk closed for triage. The latest version can be tested via the `react-charts@beta` tag. Documentation is in the process of being upgraded, but thankfully, everything is fully typed now, so you can explore the API that way for now.

If, *after testing or playing with the v3 beta*, you believe your issue is still not addressed or relevant, feel free to open a new issue.
