### ISSUE TITLE
Brushing doesn't work on ordinal time

### ISSUE THREAD

**Issue by dkaushik95** [tannerlinsley/react-charts#125]
When we use `ordinal` type for the primary axis, brushing gives an error

![image](https://user-images.githubusercontent.com/8481567/93822238-eee60000-fc2d-11ea-98ff-562827b20226.png)

I am trying to use a time system for the x-axis that can be localized and the only way to do this is to use ordinal.

**Comment by tannerlinsley** [comment]
Due to a massive overhaul and rewrite of React Charts to TypeScript and a massively upgraded public API, this issue is being bulk closed for triage. The latest version can be tested via the `react-charts@beta` tag. Documentation is in the process of being upgraded, but thankfully, everything is fully typed now, so you can explore the API that way for now.

If, *after testing or playing with the v3 beta*, you believe your issue is still not addressed or relevant, feel free to open a new issue.
