### ISSUE TITLE
Chart cant display properly when 0 is drawn on primary or secondary data

### ISSUE THREAD

**Issue by luizrosalba** [tannerlinsley/react-charts#126]
Every time 0 apppears on primary or secondary data chart cant display properly 

![image](https://user-images.githubusercontent.com/676230/94005944-7427fc80-fd75-11ea-87db-7bf1cefed193.png)

![image](https://user-images.githubusercontent.com/676230/94006002-8b66ea00-fd75-11ea-828d-4594f81558b0.png)

this error does not occur when non zero data is drawn 

my solution was adding a condition for not returning zero on makeSeries 
return {
        primary: x?x:1,
        secondary: y?y:1,
        radius: r
      };

**Comment by darthzeran** [comment]
Yah I am seeing this too.
Some of the examples here have a 0 in them, but if I copy the random data, and insert more than one 0 in it, it looks like the above image.

**Comment by christiankaindl** [comment]
I just ran into the same problem: Zeros on our secondary axis threw of the whole chart.

The workaround that worked for us, oddly enough, was to convert the number values of the axis into a string:

``` js
const data = useMemo(() => {
    return [{
      label: 'Test',
      data: dataFromDB.map((item) => {
        return {
          primary: item.value1,
          secondary: `${item.valueWithZerosSometimes}` // <- THE FIX; Alternative: `item.valueWithZerosSometimes + ""` (both convert the number value into a string
        }
      })
    }]
  }, [dataFromDB])
```

**Comment by tannerlinsley** [comment]
Due to a massive overhaul and rewrite of React Charts to TypeScript and a massively upgraded public API, this issue is being bulk closed for triage. The latest version can be tested via the `react-charts@beta` tag. Documentation is in the process of being upgraded, but thankfully, everything is fully typed now, so you can explore the API that way for now.

If, *after testing or playing with the v3 beta*, you believe your issue is still not addressed or relevant, feel free to open a new issue.
