### ISSUE TITLE
chart doesnt show if there is one value in array

### ISSUE THREAD

**Issue by bipindubey-technoark** [tannerlinsley/react-charts#127]
```
const trend = React.useMemo(
        () => [
            {
                label: 'Series 1',
                data: [[0,1]],
            },
        ],
        []
    );
```
this is my code when i have one element in array then it doesnt show the graph .. if it is more than 2 then graph is visible...
is there any solution so that i can draw chart for only 1 element

**Comment by qburst-neswine** [comment]
Any update for this issue? Is there a way I can define my domain of the axis?

**Comment by tannerlinsley** [comment]
Due to a massive overhaul and rewrite of React Charts to TypeScript and a massively upgraded public API, this issue is being bulk closed for triage. The latest version can be tested via the `react-charts@beta` tag. Documentation is in the process of being upgraded, but thankfully, everything is fully typed now, so you can explore the API that way for now.

If, *after testing or playing with the v3 beta*, you believe your issue is still not addressed or relevant, feel free to open a new issue.
