### ISSUE TITLE
Brushing doesn't work on mobile

### ISSUE THREAD

**Issue by Zinston** [tannerlinsley/react-charts#128]
Brushing doesn't work on Android or on Linux Chrome Devtools mobile mode. My guess is that mouse events are listened to but pointer events were forgotten ?

**Comment by tannerlinsley** [comment]
For now, yes that is the case.

Tanner Linsley

**Comment by tannerlinsley** [comment]
Due to a massive overhaul and rewrite of React Charts to TypeScript and a massively upgraded public API, this issue is being bulk closed for triage. The latest version can be tested via the `react-charts@beta` tag. Documentation is in the process of being upgraded, but thankfully, everything is fully typed now, so you can explore the API that way for now.

If, *after testing or playing with the v3 beta*, you believe your issue is still not addressed or relevant, feel free to open a new issue.
