### ISSUE TITLE
Line not drawn between points on line graph

### ISSUE THREAD

**Issue by darthzeran** [tannerlinsley/react-charts#129]
So I either misread one of the doc examples, or that example has been updated, but I was creating my data points in my series in a tuple, rather than an object.
```
[
			{
				label: 'Label',
				data: [[x,y], [x1,y1],[x2,y2]],
			},
		]
```
And this was working somehow.  IDK how, but it was.  AND my graph was having a line drawn from point to point to point.

However, now that I have changed it so the data is an object with a primary and secondary value, the line only drawn to some of the points.

Example: 
![image](https://user-images.githubusercontent.com/21347766/94602562-47cb1f00-0252-11eb-9df0-4f8376926e77.png)

And when I switch back to using a tuple of [x, y] instead or {primary: x, secondary:y}, it works like so:
![image](https://user-images.githubusercontent.com/21347766/94603380-65e54f00-0253-11eb-8e55-d59d5f85dc31.png)

You can also tell between pictures, that all of my data values with a value of 0 do not show up when I label data as {primary and secondary}.  I am continually looking for a fix, but any help or tips would be appreciated!

**Comment by tannerlinsley** [comment]
Due to a massive overhaul and rewrite of React Charts to TypeScript and a massively upgraded public API, this issue is being bulk closed for triage. The latest version can be tested via the `react-charts@beta` tag. Documentation is in the process of being upgraded, but thankfully, everything is fully typed now, so you can explore the API that way for now.

If, *after testing or playing with the v3 beta*, you believe your issue is still not addressed or relevant, feel free to open a new issue.
