### ISSUE TITLE
Question about line chart example

### ISSUE THREAD

**Issue by darthzeran** [tannerlinsley/react-charts#130]
On this line chart example, https://react-charts.tanstack.com/examples/line, 
If I console log the data, it looks like this
```
// ... here meaning we are trimming the massive data object
[{
    "label": "Series 1",
    "data": [{
      "primary": "2020-09-29T19:00:00.000Z",
      "secondary": 2
    }, {
      "primary": "2020-09-30T19:00:00.000Z",
      "secondary": 22
    }, ...]
  }, {
    ...{
      "primary": "2020-10-07T19:00:00.000Z",
      "secondary": 72
    },
    {
      "primary": "2020-10-08T19:00:00.000Z",
      "secondary": 2
    }]
}]

```

However, if I insert this code into the example
```
	const data = React.useMemo(() => {
		return THAT_SAME_DATA_OBJECT_I_LOGGED
	}, [])

or


	const data = React.useMemo(() => 
		HAT_SAME_DATA_OBJECT_I_LOGGED
	, [])
```
The example either breaks or does not show up.
Is there a reason to that? Because that reason may be useful in knowing how to properly create and send data to the Chart.

**Comment by tannerlinsley** [comment]
Due to a massive overhaul and rewrite of React Charts to TypeScript and a massively upgraded public API, this issue is being bulk closed for triage. The latest version can be tested via the `react-charts@beta` tag. Documentation is in the process of being upgraded, but thankfully, everything is fully typed now, so you can explore the API that way for now.

If, *after testing or playing with the v3 beta*, you believe your issue is still not addressed or relevant, feel free to open a new issue.
