### ISSUE TITLE
Export Functionality

### ISSUE THREAD

**Issue by danilocecilia** [tannerlinsley/react-charts#137]
Hi All,

I've tried to find export functionality for this lib and couldn't find anything. Am I missing smt or the liv doesn't provide any export functionality as for now?

**Comment by dasubermanmind** [comment]
Can you show an example of what you are trying to do?

**Comment by tannerlinsley** [comment]
Due to a massive overhaul and rewrite of React Charts to TypeScript and a massively upgraded public API, this issue is being bulk closed for triage. The latest version can be tested via the `react-charts@beta` tag. Documentation is in the process of being upgraded, but thankfully, everything is fully typed now, so you can explore the API that way for now.

If, *after testing or playing with the v3 beta*, you believe your issue is still not addressed or relevant, feel free to open a new issue.
