### ISSUE TITLE
Can we change color of line charts or column charts

### ISSUE THREAD

**Issue by NupurThakur27** [tannerlinsley/react-charts#139]

**Comment by RahmanMonjur** [comment]
@NupurThakur27 did you find the solution?

**Comment by X-lem** [comment]
Attempted this via forcing CSS (for the bar chart). I don't think it's possible (or I should say it might be, but probably super janky). It seems **some** elements are deleted and recreated on hover. Couldn't figure it out :( Custom colors would be a great addition to this. Honestly I take it over pie charts ;)

**Comment by tannerlinsley** [comment]
Due to a massive overhaul and rewrite of React Charts to TypeScript and a massively upgraded public API, this issue is being bulk closed for triage. The latest version can be tested via the `react-charts@beta` tag. Documentation is in the process of being upgraded, but thankfully, everything is fully typed now, so you can explore the API that way for now.

If, *after testing or playing with the v3 beta*, you believe your issue is still not addressed or relevant, feel free to open a new issue.
