### ISSUE TITLE
First and last bars do not display correctly on bar chart with time axis

### ISSUE THREAD

**Issue by arustle** [tannerlinsley/react-charts#140]
The first and last bars in bar chart with a time-axis do not display properly.  The first bar overlaps and covers the y-axis.  The last bar is half the width when compared to the other bars.

https://codesandbox.io/s/quizzical-hooks-4dpmy

![image](https://user-images.githubusercontent.com/44350419/100551568-7748d880-324f-11eb-9eed-a74a9d3fec6b.png)

**Comment by funkju** [comment]
I'm seeing this as well.

**Comment by jatazoulja** [comment]
same here! Y axes are being are being croped, even using line, 
in my case its line, not bar, 
it acquires when ordinal is use:
 
```javascript
const axes = React.useMemo(
    () => [
      { primary: true, type: '**ordinal**', position: 'bottom' },
      { position: 'left', type: 'linear', stacked: true },
    ],
    []
  );
  );
```

its ok when linear is use:
```javascript
  const axes = React.useMemo(
    () => [
      { primary: true, type: 'linear', position: 'bottom' },
      { position: 'left', type: 'linear', stacked: true },
    ],
    []
  );
```
wierd result if I change time to linear:
![image](https://user-images.githubusercontent.com/361771/112789285-55d9eb00-908f-11eb-8639-677e44e2b2a8.png)

**Comment by prandev01** [comment]
Hello, Team.

I am also having this issue.
Isn't there any workaround?

**Comment by tannerlinsley** [comment]
Due to a massive overhaul and rewrite of React Charts to TypeScript and a massively upgraded public API, this issue is being bulk closed for triage. The latest version can be tested via the `react-charts@beta` tag. Documentation is in the process of being upgraded, but thankfully, everything is fully typed now, so you can explore the API that way for now.

If, *after testing or playing with the v3 beta*, you believe your issue is still not addressed or relevant, feel free to open a new issue.
