### ISSUE TITLE
Is the react-charts free?

### ISSUE THREAD

**Issue by kamleshwebtech** [tannerlinsley/react-charts#146]
Is the react-charts free? Kindly confirm and add a note of pricing term in readme.me file, if any. Thanks a lot.

**Comment by AChillFeeder** [comment]
Yes It is, it has an MIT license

**Comment by tannerlinsley** [comment]
Due to a massive overhaul and rewrite of React Charts to TypeScript and a massively upgraded public API, this issue is being bulk closed for triage. The latest version can be tested via the `react-charts@beta` tag. Documentation is in the process of being upgraded, but thankfully, everything is fully typed now, so you can explore the API that way for now.

If, *after testing or playing with the v3 beta*, you believe your issue is still not addressed or relevant, feel free to open a new issue.
