### ISSUE TITLE
Side Axis Numbers Not Showing Fully

### ISSUE THREAD

**Issue by bryanlubay** [tannerlinsley/react-charts#147]
Hello,

My app at https://bryanlubay.herokuapp.com/ has an issue with displaying the left side axis numbers. After inspecting it, it will show the full numbers and it will stay like that if you close the inspector. How can I get it to fully display the numbers correctly without having to inspect it first? The bottom right number on the bottom axis also gets slightly cut off. Thanks in advance!

![image](https://user-images.githubusercontent.com/51036864/103030585-f230a680-4510-11eb-8791-a4d6330b3af8.png)
![image](https://user-images.githubusercontent.com/51036864/103030631-08d6fd80-4511-11eb-9c82-96ae8b4de0c8.png)

**Comment by bryanlubay** [comment]
So I kinda fixed it by initializing the numbers to 10,000 instead of 0 lol

**Comment by tannerlinsley** [comment]
Due to a massive overhaul and rewrite of React Charts to TypeScript and a massively upgraded public API, this issue is being bulk closed for triage. The latest version can be tested via the `react-charts@beta` tag. Documentation is in the process of being upgraded, but thankfully, everything is fully typed now, so you can explore the API that way for now.

If, *after testing or playing with the v3 beta*, you believe your issue is still not addressed or relevant, feel free to open a new issue.
