### ISSUE TITLE
Support for Vite/Snowpack (unbundled frontend build tools)

### ISSUE THREAD

**Issue by stephen-last** [tannerlinsley/react-charts#149]
When I try to use `react-charts` with [vitejs](https://vitejs.dev/) I get this error when running the dev server:

````
[plugin:vite:import-analysis] Failed to resolve entry for package "react-charts". The package may have incorrect main/module/exports specified in its package.json.
/.../MyChart.jsx
````

Is there something I can do to fix this myself, or does `react-charts` need to be updated..?

**Comment by stephen-last** [comment]
Ok, I'm now trying [snowpack](https://www.snowpack.dev/), another unbundled build tool in dev, and I'm running into the same issue. It seems `module` in `package.json` needs to be `dist/react-charts.min.mjs` rather than `dist/react-charts.mjs`. 

Changing `module` to `dist/react-charts.min.mjs` in `node_modules\react-charts\package.json` after installing gets me a little further, that is, the snowpack dev server starts up. However, in the browser I then get this error:

````
Unhandled Runtime Error
Uncaught ReferenceError: require is not defined
http://localhost:8080/web_modules/react-charts.js [:3:10055]
````

...which is pointing to `var L=require("performance-now")` in `react-charts.min.mjs`.

It looks like this `require()` is the only one, and possibly the only thing stopping `react-charts` from working with unbundled build tools.

**Comment by tannerlinsley** [comment]
Due to a massive overhaul and rewrite of React Charts to TypeScript and a massively upgraded public API, this issue is being bulk closed for triage. The latest version can be tested via the `react-charts@beta` tag. Documentation is in the process of being upgraded, but thankfully, everything is fully typed now, so you can explore the API that way for now.

If, *after testing or playing with the v3 beta*, you believe your issue is still not addressed or relevant, feel free to open a new issue.

**Comment by olee** [comment]
Still happens in beta

**Comment by samuthekid** [comment]
still happening here :s

![image](https://user-images.githubusercontent.com/6068533/213514400-b58e448f-b272-431b-a732-afa4f155e5c0.png)

**Comment by HCAWN** [comment]
The experience as @stephen-last has described it is exactly what I find. React Charts V3 doesn't appear to be moving forwards (minimally since this was closed 2 years ago) and has little documentation allowing a migration to take place from the old beta to the new beta.
Now with new projects using Vite but still wanting to make something that functions as before seems impossible.
@tannerlinsley you're a busy chap and have new amazing projects so is React Charts just becoming a zombie with 6 commits in 2023?
If there _is_ capacity for little contributions, should they not be made to V2 that still has the most downloads and give up on V3?
