### ISSUE TITLE
 Received NaN for the `height` and 'y' attribute. 

### ISSUE THREAD

**Issue by rpnXwork** [tannerlinsley/react-charts#150]
all time get 
Warning: Received NaN for the `height` attribute. If this is expected, cast the value to a string.
and 
Received NaN for the `y` attribute. If this is expected, cast the value to a string.
in Column Chart

errors will disappear. when I add on 961 string
 x: xStart || 0,
 y: yStart || 0,
 width: width || 0,
 height: height || 0,

and errors will disappear.

**Comment by malinda1986** [comment]
Getting the same error. any fix?

**Comment by izziaraffaele** [comment]
I had the same issue but for me it is solved in the `next` version

**Comment by tannerlinsley** [comment]
Due to a massive overhaul and rewrite of React Charts to TypeScript and a massively upgraded public API, this issue is being bulk closed for triage. The latest version can be tested via the `react-charts@beta` tag. Documentation is in the process of being upgraded, but thankfully, everything is fully typed now, so you can explore the API that way for now.

If, *after testing or playing with the v3 beta*, you believe your issue is still not addressed or relevant, feel free to open a new issue.
