### ISSUE TITLE
Allow the SecondaryCursor value of sync'd cursors to match the Y-axis value of each sub-chart

### ISSUE THREAD

**Issue by howardmalec** [tannerlinsley/react-charts#152]
Sync'd cursors that display across multiple charts currently correspond to the primaryCursor & secondaryCursor of the chart that's hovered over.

<img width="1223" alt="Screen Shot 2021-02-20 at 4 59 45 PM" src="https://user-images.githubusercontent.com/33383671/108612414-6f578b00-739d-11eb-912f-b6cc616603bd.png">

While the primaryCursor works as expected, ideally we'd have an option to set the secondaryCursor value to the Y-axis of each sub chart (independent of the Y-axis value of the chart that's hovered over). 

Following this logic in the image above - the Y axis for chart #2, Series #1 should be 60 instead 90. 

This could be achieved by allowing the secondaryCursor to be specified at the chart level via a reference to the global "activeSeriesIndex" and "activeDatumIndex" that are set by the hover-over criteria. 

The [custom styles code sandbox](https://react-charts.tanstack.com/examples/custom-styles) demonstrates a usecase around setting the activeSeriesIndex and activeDatumIndex via a the state var.

**Comment by howardmalec** [comment]
The other workaround: we could expand the logic around tooltips so on hover the corresponding tooltip shows up on each sub-chart.

**Comment by howardmalec** [comment]
Tutorial available here that outlines a potential workflow: https://swizec.com/blog/tooltips-and-state-across-various-d3-charts-in-a-react-dashboard

**Comment by tannerlinsley** [comment]
Due to a massive overhaul and rewrite of React Charts to TypeScript and a massively upgraded public API, this issue is being bulk closed for triage. The latest version can be tested via the `react-charts@beta` tag. Documentation is in the process of being upgraded, but thankfully, everything is fully typed now, so you can explore the API that way for now.

If, *after testing or playing with the v3 beta*, you believe your issue is still not addressed or relevant, feel free to open a new issue.
