### ISSUE TITLE
onClick event is called when brushing

### ISSUE THREAD

**Issue by oripessach** [tannerlinsley/react-charts#153]
The onClick event is called when the user finishes a brushing drag on the graph. The datum being passed is the one closest to the pointer position at the end of the drag, regardless of whether that datum was clicked or not. 

Since the original click event is not passed through to the onClick handler, I can't even try to determine whether the click happened within the bounds of the datum or not.

**Comment by tannerlinsley** [comment]
Due to a massive overhaul and rewrite of React Charts to TypeScript and a massively upgraded public API, this issue is being bulk closed for triage. The latest version can be tested via the `react-charts@beta` tag. Documentation is in the process of being upgraded, but thankfully, everything is fully typed now, so you can explore the API that way for now.

If, *after testing or playing with the v3 beta*, you believe your issue is still not addressed or relevant, feel free to open a new issue.
