### ISSUE TITLE
The library is not working with react 17.0.1

### ISSUE THREAD

**Issue by Svetloslav15** [tannerlinsley/react-charts#160]
I have an app that is running on 17.0.1 version of React and when I try to install react-charts I face an error that the library cannot work with newest version of react.

**Comment by tannerlinsley** [comment]
Due to a massive overhaul and rewrite of React Charts to TypeScript and a massively upgraded public API, this issue is being bulk closed for triage. The latest version can be tested via the `react-charts@beta` tag. Documentation is in the process of being upgraded, but thankfully, everything is fully typed now, so you can explore the API that way for now.

If, *after testing or playing with the v3 beta*, you believe your issue is still not addressed or relevant, feel free to open a new issue.
