### ISSUE TITLE
TypeScript Support

### ISSUE THREAD

**Issue by alii** [tannerlinsley/react-charts#164]
Before I start, thank you very much for all your hard work on OSS, Tanner! react-charts and react-query are really awesome libs! We really appreciate all the time you spend working on them

As more people are learning & moving to TypeScript it would be really great to see it supported here. There was an issue raised almost three years ago - #26 - but I think that there has been a lot of change in the js/react ecosystem that justifies a new issue. TS has been a prominent tool of 2020/21. Show us TS fans some love 🤓

**Comment by tannerlinsley** [comment]
Due to a massive overhaul and rewrite of React Charts to TypeScript and a massively upgraded public API, this issue is being bulk closed for triage. The latest version can be tested via the `react-charts@beta` tag. Documentation is in the process of being upgraded, but thankfully, everything is fully typed now, so you can explore the API that way for now.

If, *after testing or playing with the v3 beta*, you believe your issue is still not addressed or relevant, feel free to open a new issue.
