### ISSUE TITLE
Tooltip zIndex

### ISSUE THREAD

**Issue by nemozar** [tannerlinsley/react-charts#167]
When you display several graphs next to it, the tooltip is overlapped by the adjacent one. All charts have zIndex: 100, because they are in the component that overlapped the tooltip.

"version": "2.0.2-next.22"

![Снимок экрана от 2021-04-21 11-52-10](https://user-images.githubusercontent.com/4721820/115526265-85e46a80-a298-11eb-9aed-ff28c781d202.png)

reverse does not overlap
![Снимок экрана от 2021-04-21 11-59-39](https://user-images.githubusercontent.com/4721820/115526896-2dfa3380-a299-11eb-88ba-e4f5afaad6f0.png)

**Comment by tannerlinsley** [comment]
Due to a massive overhaul and rewrite of React Charts to TypeScript and a massively upgraded public API, this issue is being bulk closed for triage. The latest version can be tested via the `react-charts@beta` tag. Documentation is in the process of being upgraded, but thankfully, everything is fully typed now, so you can explore the API that way for now.

If, *after testing or playing with the v3 beta*, you believe your issue is still not addressed or relevant, feel free to open a new issue.
