### ISSUE TITLE
All of the examples are broke

### ISSUE THREAD

**Issue by mikestopcontinues** [tannerlinsley/react-charts#187]
Hey, I'm seeing the same error across the board:

<img width="1047" alt="Screen Shot 2021-05-20 at 7 35 05 PM" src="https://user-images.githubusercontent.com/150434/119030997-32853b00-b970-11eb-9062-21d882c4940f.png">

**Comment by f-felicio** [comment]
I can see the examples by clicking **'Open in CodeSandbox'** and then clicking **'Add performance-now as dependency'**.

**Comment by JiangWeixian** [comment]
same issue

**Comment by tannerlinsley** [comment]
Due to a massive overhaul and rewrite of React Charts to TypeScript and a massively upgraded public API, this issue is being bulk closed for triage. The latest version can be tested via the `react-charts@beta` tag. Documentation is in the process of being upgraded, but thankfully, everything is fully typed now, so you can explore the API that way for now.

If, *after testing or playing with the v3 beta*, you believe your issue is still not addressed or relevant, feel free to open a new issue.
