### ISSUE TITLE
Custom ticks 

### ISSUE THREAD

**Issue by Alhoucine-Yacine** [tannerlinsley/react-charts#190]
Hey,

I'm trying to make a chart which has in x-axis some angles. Basically, I want to have only the main angles, such as 90°, 180° and 360°, so I wrote this code : 

const axes = React.useMemo(
        () => [
          { primary: true,
            type: 'linear',
            position: 'bottom', 
            snapCursor : true ,
            hardMin  : 0, 
            hardMax : 360,
            base : 360,
            stacked : false,
            tickValues : [0,90,180,270,360]
             },
          { type: 'linear', position: 'left'}
        ],
        []
      ); 

However, it changes absolutely nothing when I precised the tickValues. Any ideas ??

**Comment by tannerlinsley** [comment]
Due to a massive overhaul and rewrite of React Charts to TypeScript and a massively upgraded public API, this issue is being bulk closed for triage. The latest version can be tested via the `react-charts@beta` tag. Documentation is in the process of being upgraded, but thankfully, everything is fully typed now, so you can explore the API that way for now.

If, *after testing or playing with the v3 beta*, you believe your issue is still not addressed or relevant, feel free to open a new issue.
