### ISSUE TITLE
Missing index argument for user provided format function

### ISSUE THREAD

**Issue by bezsinnyidmytro** [tannerlinsley/react-charts#200]
**User provided `format` function doesn't receive any arguments except the only one - axis raw label. While according to the flow it should receive at least one more argument - label index**

I wasn't able to use `ticks` or `maxTicksCount` with axis type `ordinal` to limit or arbitrary skip some labels.
So `format` function is the only option for me here.

Must say that this bug is not reproduced on `next` branch only on `master`
I found the code responsible for this misbehaviour and can provide a PR for `master` branch if it is OK
to fix something on `master` which is already working fine on `next`

Big thanks for this beautiful charts library, animated chart looks especially awesome.

**Comment by tannerlinsley** [comment]
Due to a massive overhaul and rewrite of React Charts to TypeScript and a massively upgraded public API, this issue is being bulk closed for triage. The latest version can be tested via the `react-charts@beta` tag. Documentation is in the process of being upgraded, but thankfully, everything is fully typed now, so you can explore the API that way for now.

If, *after testing or playing with the v3 beta*, you believe your issue is still not addressed or relevant, feel free to open a new issue.
