### ISSUE TITLE
Provide a changelog

### ISSUE THREAD

**Issue by ThiefMaster** [tannerlinsley/react-charts#205]
Right now the version situation is extremely confusing:

- `@latest` version is 2.0.0-beta.7
- there's a `2.1.0-next.2`
- there's a 2.0.2 non-beta release

My code breaks when I install 2.0.2 instead of the 2.0.0 beta, so it looks like there are breaking changes. But without a changelog that's all I can see - and I don't think a user of a library should have to dig through commit logs to figure out what changed between versions..

**Comment by tannerlinsley** [comment]
Due to a massive overhaul and rewrite of React Charts to TypeScript and a massively upgraded public API, this issue is being bulk closed for triage. The latest version can be tested via the `react-charts@beta` tag. Documentation is in the process of being upgraded, but thankfully, everything is fully typed now, so you can explore the API that way for now.

If, *after testing or playing with the v3 beta*, you believe your issue is still not addressed or relevant, feel free to open a new issue.
