### ISSUE TITLE
Strange Tooltip behavior on line graph with series

### ISSUE THREAD

**Issue by SMSmith** [tannerlinsley/react-charts#207]
![image](https://user-images.githubusercontent.com/1759737/123313057-16d4fd80-d4f7-11eb-9e6f-bc02b58c0352.png)

Version: ^2.0.0-beta.7

The tooltip should show a bunch of email addresses (the labels).  
`
const axes = useMemo(() => [
        { primary: true, type: 'utc', position: 'bottom' },
        { type: 'linear', position: 'left' }
    ], [])
`
`
const series = useMemo(() => ({
        type: 'line'
    }),[]);
`
`<Chart data={data} axes={axes} series={series} tooltip />`

**Comment by tannerlinsley** [comment]
Due to a massive overhaul and rewrite of React Charts to TypeScript and a massively upgraded public API, this issue is being bulk closed for triage. The latest version can be tested via the `react-charts@beta` tag. Documentation is in the process of being upgraded, but thankfully, everything is fully typed now, so you can explore the API that way for now.

If, *after testing or playing with the v3 beta*, you believe your issue is still not addressed or relevant, feel free to open a new issue.
