### ISSUE TITLE
Put line to bottom Line chart when value is zero

### ISSUE THREAD

**Issue by luisleong** [tannerlinsley/react-charts#208]
Hello, how can I do to put this line to the bottom of the chart instead of the middle? Thanks.
![image](https://user-images.githubusercontent.com/18541440/123990037-6b64f680-d997-11eb-9a44-5b43287d5cb8.png)

**Comment by tannerlinsley** [comment]
Due to a massive overhaul and rewrite of React Charts to TypeScript and a massively upgraded public API, this issue is being bulk closed for triage. The latest version can be tested via the `react-charts@beta` tag. Documentation is in the process of being upgraded, but thankfully, everything is fully typed now, so you can explore the API that way for now.

If, *after testing or playing with the v3 beta*, you believe your issue is still not addressed or relevant, feel free to open a new issue.
