### ISSUE TITLE
Axis Label/Title

### ISSUE THREAD

**Issue by Danjosh0211** [tannerlinsley/react-charts#210]
Is there any way to add axis titles, I can't find it in the documentation.
Would be nice to insert { label: "My title for the axis" } in the axis items. Just a textual string.

**Comment by tannerlinsley** [comment]
I’ll be adding this feature soon. It requires a lot of new auto-margin logic but shouldn’t be too bad.

**Comment by Danjosh0211** [comment]
Thanks, btw great library, appreciate the quick response.

For everyone else with this same issue too, i've managed a workaround for the time being using a bit of hacky css so here's my solution.
CSS
```
.graph_y_axis_label {
  font-size: 1rem;
  color: black;
  letter-spacing: 1px;
  padding: 5px 200px;
  margin: 0 0 10px 0;
  line-height: 24px;
  position: absolute;
  bottom: 0;
  left: 0;
  margin-left: -30px;
  transform: rotate(270deg);
  transform-origin: 0 0;
}
.graph_x_axis_label {
  font-size: 1rem;
  color: black;
  letter-spacing: 1px;
  text-align: center;
}
aside{
  display: block;
position: relative;
}
```
HTML:
```
    <>
    <aside>
      <p class="graph_y_axis_label">Score</p>
      <div
        style={{
          height: `${height}px`,
        }}
      >

        <Chart data={data} series={series} axes={axes} tooltip={tooltip}/>
      </div>
    </aside>
    <p class="graph_x_axis_label">Attempts</p>

    </>

```

**Comment by tannerlinsley** [comment]
Due to a massive overhaul and rewrite of React Charts to TypeScript and a massively upgraded public API, this issue is being bulk closed for triage. The latest version can be tested via the `react-charts@beta` tag. Documentation is in the process of being upgraded, but thankfully, everything is fully typed now, so you can explore the API that way for now.

If, *after testing or playing with the v3 beta*, you believe your issue is still not addressed or relevant, feel free to open a new issue.
