### ISSUE TITLE
Timeline features

### ISSUE THREAD

**Issue by vinceve** [tannerlinsley/react-charts#42]
Hey!

Sorry to mention this in your issue tracker. I am following this library and there is already some great work in here! I was looking into some charts but with timeline selection functionality. Is this possible based on this library or would it be very hard to create this? It is some kind of range selection mechanism.

**Comment by evenstephenr** [comment]
@vinceve hello 👋 

Is this still relevant to your current needs? Do you have any examples of websites or libraries that are doing this well? Lots of different 'styles' to consider here

**Comment by tannerlinsley** [comment]
Due to a massive overhaul and rewrite of React Charts to TypeScript and a massively upgraded public API, this issue is being bulk closed for triage. The latest version can be tested via the `react-charts@beta` tag. Documentation is in the process of being upgraded, but thankfully, everything is fully typed now, so you can explore the API that way for now.

If, *after testing or playing with the v3 beta*, you believe your issue is still not addressed or relevant, feel free to open a new issue.
