### ISSUE TITLE
time is not labeled correctly

### ISSUE THREAD

**Issue by edenlu** [tannerlinsley/react-charts#44]
Hi there,

When I try to plot my data in time, the x-axis show some not understandable float rather than a date. Is this a correct behavior?

Simplified version of my code is shown below
```   
function App() {
    let currentTime = new Date();
    let currentTime2 = new Date().setHours(new Date().getHours() + 1);
    let currentTime3 = new Date().setHours(new Date().getHours() + 2);
    let workerCount = {
        label: 'Worker Count',
        data: [{x: currentTime, y: 1},
               {x: currentTime2, y: 2},
               {x: currentTime3, y: 3}],
        color: "#00ff00"
    };
    let [plotData, handlePlotDataChange] = useState([workerCount]);
    let [axes, handleAxesChange] = useState([
        { type: 'linear', position: 'left' },
        { primary: true, type: 'time', position: 'bottom' }
    ]);

    return (
            <div style={{ width: '800px', height: '600px', 'marginTop': '10px' }}>
                <Chart data={plotData}
                    axes={axes}
                    primaryCursor
                    secondaryCursor
                    tooltip />
            </div>
        </div>
    );
}
```

Output:
![Time is not labeled correct](https://user-images.githubusercontent.com/11380330/68504552-0d135f00-021a-11ea-8994-7fc3669f77c0.png)

**Comment by mddanishyusuf** [comment]
Same problem I'm facing.

**Comment by tannerlinsley** [comment]
This is because you need to round minutes and milliseconds too. Even if you have equally spaced hourly items, d3-scale is finding the least common denominator for the time and if it includes smaller time units than an hour, then the specificity will show down the hour. Unfortunately, the default time formatter doesn't show the *full* time when doing millisecond display, so you end up just seeing the milliseconds.

**Comment by darthzeran** [comment]
is this behavior expected to always remain?
