### ISSUE TITLE
Bar example not in sync with current version

### ISSUE THREAD

**Issue by ontoport** [tannerlinsley/react-charts#48]
I tried to use the bar example at [https://react-charts.js.org/examples/bar](https://react-charts.js.org/examples/bar). It doesn't seem to be in sync with the current version. Could you please update this example or provide an example at some other place? It would be most helpful if the kind of needed parameterization would become clear. Thanks!

**Comment by tannerlinsley** [comment]
Due to a massive overhaul and rewrite of React Charts to TypeScript and a massively upgraded public API, this issue is being bulk closed for triage. The latest version can be tested via the `react-charts@beta` tag. Documentation is in the process of being upgraded, but thankfully, everything is fully typed now, so you can explore the API that way for now.

If, *after testing or playing with the v3 beta*, you believe your issue is still not addressed or relevant, feel free to open a new issue.
