### ISSUE TITLE
Chart key/summary

### ISSUE THREAD

**Issue by crobinson42** [tannerlinsley/react-charts#51]
Awesome lib! I'm wondering if this library can render color coordinated keys that correlate to a chart?

**Comment by evenstephenr** [comment]
@crobinson42 can you give a little more detail on what keys you'd like to see correlated, or let us know if this question has been resolved by a newer version of `react-charts`?

I see in the docs tooltips support color matching series natively https://react-charts.tanstack.com/examples/tooltip-options

**Comment by tannerlinsley** [comment]
Due to a massive overhaul and rewrite of React Charts to TypeScript and a massively upgraded public API, this issue is being bulk closed for triage. The latest version can be tested via the `react-charts@beta` tag. Documentation is in the process of being upgraded, but thankfully, everything is fully typed now, so you can explore the API that way for now.

If, *after testing or playing with the v3 beta*, you believe your issue is still not addressed or relevant, feel free to open a new issue.
