### ISSUE TITLE
bar chart with scale breaks

### ISSUE THREAD

**Issue by rshahhutch** [tannerlinsley/react-charts#53]
Hi! 
I have many bar charts with outliers that have really large values compared to other items in the bar chart.
![barchart](https://user-images.githubusercontent.com/17936265/72005871-65a7ae00-3203-11ea-8d3e-07daa1530890.png)

I would like to crop the long bars, so that the chart takes less space. Something like this: (ignore the orientation). Does your bar chart handle scale breaks?

![barchart_scaleBreak](https://user-images.githubusercontent.com/17936265/72005899-748e6080-3203-11ea-8db1-d6b79b0621c0.png)

**Comment by tannerlinsley** [comment]
Due to a massive overhaul and rewrite of React Charts to TypeScript and a massively upgraded public API, this issue is being bulk closed for triage. The latest version can be tested via the `react-charts@beta` tag. Documentation is in the process of being upgraded, but thankfully, everything is fully typed now, so you can explore the API that way for now.

If, *after testing or playing with the v3 beta*, you believe your issue is still not addressed or relevant, feel free to open a new issue.
