### ISSUE TITLE
How to display legend?

### ISSUE THREAD

**Issue by pasan9** [tannerlinsley/react-charts#56]
Hi, the Charts work great, is there an API that I can use to show the legend similar to re-charts?

**Comment by alvarolaserna** [comment]
Is there any way to get the legend colors used in the charts mapped with the labels so I can create a custom legend myself?

**Comment by RobertMcReed** [comment]
My workaround to this was to manually set the color for my groups based on their index, and then access that color again via index in a custom Legend that I created.

You can access the list of default colors from the source: https://github.com/tannerlinsley/react-charts/blob/4217531a930db36b66e3a145096faf2c9e64f5b1/src/components/Chart.js#L30

At the time of writing that looks like this:

```
const defaultColorScheme = [
  '#0f83ab',
  '#faa43a',
  '#ff4e4e',
  '#53cfc9',
  '#a2d925',
  '#decf3f',
  '#734fe9',
  '#cd82ad',
  '#006d92',
  '#de7c00',
  '#f33232',
  '#3f9a80',
  '#53c200',
  '#d7af00',
  '#4c26c9',
  '#d44d99',
]
```

**Comment by tannerlinsley** [comment]
Due to a massive overhaul and rewrite of React Charts to TypeScript and a massively upgraded public API, this issue is being bulk closed for triage. The latest version can be tested via the `react-charts@beta` tag. Documentation is in the process of being upgraded, but thankfully, everything is fully typed now, so you can explore the API that way for now.

If, *after testing or playing with the v3 beta*, you believe your issue is still not addressed or relevant, feel free to open a new issue.
