### ISSUE TITLE
How to change decimals in tooltip display

### ISSUE THREAD

**Issue by phil-saam** [tannerlinsley/react-charts#68]
Is there a way to allow the tooltip to display another digit?  for example 1.1 instead of 1?

**Comment by KozhokarAlex** [comment]
@H-Pylori  I have the same question, did you find an answer ?

**Comment by H-Pylori** [comment]
Ahh, I did figure this out it took me a while but I had to change a setting in the package.  I can't remember where it was but there is a toPrecision() or fixed() setting in there and I did some trial and error until I got it to behave the way I wanted.  I will go back and see if I can find where I ended up changing that.

**Comment by tannerlinsley** [comment]
Due to a massive overhaul and rewrite of React Charts to TypeScript and a massively upgraded public API, this issue is being bulk closed for triage. The latest version can be tested via the `react-charts@beta` tag. Documentation is in the process of being upgraded, but thankfully, everything is fully typed now, so you can explore the API that way for now.

If, *after testing or playing with the v3 beta*, you believe your issue is still not addressed or relevant, feel free to open a new issue.
