### ISSUE TITLE
Graph is clipped on the right

### ISSUE THREAD

**Issue by bvelasquez** [tannerlinsley/react-charts#69]
How do I prevent clipping of the last bar?

```
<Box
            style={{
              width: "100%",
              height: "400px"
            }}
          >
            <Chart
              data={data}
              axes={axes}
              series={series}
              tooltip
              primaryCursor
              secondaryCursor
            />
 </Box>
```

![2020-04-01_13-13-15](https://user-images.githubusercontent.com/2302210/78182203-9706d300-741a-11ea-9f2f-6644e845d562.png)

**Comment by bmaupin** [comment]
In my case only the label was being cut off, not the chart itself. This is how I fixed it:

1. I have a parent `div` that contains my chart and I set the class to `ChartContainer`

    ```typescript
    <div className="ChartContainer">
      <Chart
        // ...
    ```

    https://github.com/bmaupin/covid19-trends/blob/fb4f8f6d3f3b0f7da46d5907548819e047fbfb4e/src/components/Chart.tsx#L50

1. Then I used this css to fix the issue:

    ```css
    .ChartContainer svg {
      overflow: unset !important;
    }
    ```

    https://github.com/bmaupin/covid19-trends/blob/fb4f8f6d3f3b0f7da46d5907548819e047fbfb4e/src/components/Chart.css#L6

Hope that helps!

**Comment by tannerlinsley** [comment]
Due to a massive overhaul and rewrite of React Charts to TypeScript and a massively upgraded public API, this issue is being bulk closed for triage. The latest version can be tested via the `react-charts@beta` tag. Documentation is in the process of being upgraded, but thankfully, everything is fully typed now, so you can explore the API that way for now.

If, *after testing or playing with the v3 beta*, you believe your issue is still not addressed or relevant, feel free to open a new issue.
