### ISSUE TITLE
Add support for trend line

### ISSUE THREAD

**Issue by cliffordp** [tannerlinsley/react-charts#72]
Google Charts' [trendline functionality](https://developers.google.com/chart/interactive/docs/gallery/trendlines) is a surprisingly uncommon feature among charting libraries and is very nice to have (required for some projects).

I've seen one charting library say you can write your own handler function to get all the points and then add your own trendline but why not just build it in for us?

**Comment by tannerlinsley** [comment]
Due to a massive overhaul and rewrite of React Charts to TypeScript and a massively upgraded public API, this issue is being bulk closed for triage. The latest version can be tested via the `react-charts@beta` tag. Documentation is in the process of being upgraded, but thankfully, everything is fully typed now, so you can explore the API that way for now.

If, *after testing or playing with the v3 beta*, you believe your issue is still not addressed or relevant, feel free to open a new issue.
