### ISSUE TITLE
Example of how to use data accessors doesn't define getSeries

### ISSUE THREAD

**Issue by GreenAsJade** [tannerlinsley/react-charts#74]
`      <Chart
        data={data}
        getSeries={getSeries}`

What is this "getSeries"?

It seems to be the key to understanding what is going on here.

(At least, if it isn't then some more words might help, maybe an example that renders this?)

**Comment by mrlinux1** [comment]
I have the same problem with the example and can't find any hint how to solve it.
Please provide a working example.
Many thanks in advance!

**Comment by evenstephenr** [comment]
@GreenAsJade it looks like `getSeries` might be a deprecated prop on the base `Chart` component since it doesn't seem to exist in the core API here https://github.com/tannerlinsley/react-charts/blob/next/src/components/Chart.js

Is there a specific Chart you're trying to produce and need help with? Are you extending the base Chart with a custom one not provided by the library?

Also the [docs have recently been published here](https://react-charts.tanstack.com/docs/api#data-accessors), I see the documentation you're referring to. The docs should be updated if `getSeries` its a deprecated prop.

**Comment by tannerlinsley** [comment]
Due to a massive overhaul and rewrite of React Charts to TypeScript and a massively upgraded public API, this issue is being bulk closed for triage. The latest version can be tested via the `react-charts@beta` tag. Documentation is in the process of being upgraded, but thankfully, everything is fully typed now, so you can explore the API that way for now.

If, *after testing or playing with the v3 beta*, you believe your issue is still not addressed or relevant, feel free to open a new issue.
