### ISSUE TITLE
Mixed type chart data accessor

### ISSUE THREAD

**Issue by email2vimalraj** [tannerlinsley/react-charts#77]
I'm getting the following data format:

```js
const data = [
  {
    label: "series 1",
    data: [
      { date: "2020-04-01", value: 2000, forecast: [1000, 2343] },
      { date: "2020-04-02", value: 2739, forecast: [1223, 2920] },
      { date: "2020-04-03", value: 2000, forecast: [1000, 2343] },
    ],
  },
];
```

And I'm trying to build the mixed type chart component where `value` should be rendered as a line and `forecast` data range should be rendered as a area chart. I've written the following code to render the line chart properly:

```jsx
function MyChart() {
  const series = React.useCallback((s, i) => {
    showPoints: false;
  }, []);

  const getPrimary = React.useCallback(
    (datum, i, series, seriesIndex, data) => {
      return datum.date;
    },
    []
  );

  const getSecondary = React.useCallback((datum) => datum.value, []);

  const axes = React.useMemo(
    () => [
      { primary: true, position: "bottom", type: "ordinal", show: false },
      { position: "left", type: "linear", show: false },
    ],
    []
  );

  return (
    <Chart
      data={data}
      series={series}
      axes={axes}
      getPrimary={getPrimary}
      getSecondary={getSecondary}
      tooltip
    />
  );
}
```

However, I'm confused on how do I access the forecast data range and set that range for the area chart in a mixed type. Referred the following: https://react-charts.js.org/examples/mixed-types, however I'm not much clear on how to get this worked. Kindly help.

**Comment by tannerlinsley** [comment]
Due to a massive overhaul and rewrite of React Charts to TypeScript and a massively upgraded public API, this issue is being bulk closed for triage. The latest version can be tested via the `react-charts@beta` tag. Documentation is in the process of being upgraded, but thankfully, everything is fully typed now, so you can explore the API that way for now.

If, *after testing or playing with the v3 beta*, you believe your issue is still not addressed or relevant, feel free to open a new issue.
