### ISSUE TITLE
Bar Chart - Bars too large, going off screen.

### ISSUE THREAD

**Issue by bvelasquez** [tannerlinsley/react-charts#81]
Is there a way to control the size of the bars? I'm rendering a bar chart with two values. x is a Date() for each record, and y is the values 56789 and 456789. As you can see in the image, the bars are quite large and rendering off screen.

![2020-05-01_11-27-31](https://user-images.githubusercontent.com/2302210/80831000-d9007180-8b9e-11ea-8faa-846a13222603.png)

**Comment by yanickrochon** [comment]
I have similar redrawing problems, where the initial chart renders terribly, but resizing the window _may_ fix the issue.

**Before resize, on page load**
![image](https://user-images.githubusercontent.com/78461/81985758-a7f35880-9604-11ea-90b1-cd53de198eda.png)

**After resize (a few pixels)**
![image](https://user-images.githubusercontent.com/78461/81985828-cb1e0800-9604-11ea-80c2-72392026e250.png)

**Comment by tannerlinsley** [comment]
Due to a massive overhaul and rewrite of React Charts to TypeScript and a massively upgraded public API, this issue is being bulk closed for triage. The latest version can be tested via the `react-charts@beta` tag. Documentation is in the process of being upgraded, but thankfully, everything is fully typed now, so you can explore the API that way for now.

If, *after testing or playing with the v3 beta*, you believe your issue is still not addressed or relevant, feel free to open a new issue.
