### ISSUE TITLE
Negative data causes trouble with stacked bar chart tooltip

### ISSUE THREAD

**Issue by electoys** [tannerlinsley/react-charts#82]
What is the intent of a stacked bar chart having a negative and positive component?
From calculateStackData.js:
```           // Should we use positive or negative base?
              const totalKey = datum.yValue >= 0 ? 'positive' : 'negative'
              // Assign the base
              datum.baseValue = start[totalKey]
              // Add the value to the base
              datum.totalValue =
                datum.baseValue + (validPoint ? datum.yValue : 0)
              // Update the totals
              scaleTotals[secondaryAxisIndex][d.primary][totalKey] =
                datum.totalValue
```
In the tooltip there is only one Total and it's not calculated correctly.  Anyone know the reason for the more complex collection of positive and negative totals?
![stackedData_TotalData_bug](https://user-images.githubusercontent.com/22280350/81021042-382ce300-8e38-11ea-9e5a-315f17f75391.jpg)

**Comment by tannerlinsley** [comment]
Due to a massive overhaul and rewrite of React Charts to TypeScript and a massively upgraded public API, this issue is being bulk closed for triage. The latest version can be tested via the `react-charts@beta` tag. Documentation is in the process of being upgraded, but thankfully, everything is fully typed now, so you can explore the API that way for now.

If, *after testing or playing with the v3 beta*, you believe your issue is still not addressed or relevant, feel free to open a new issue.
