### ISSUE TITLE
Broken styles in Safari 13.1.1 (13609.2.9.1.3)

### ISSUE THREAD

**Issue by KozhokarAlex** [tannerlinsley/react-charts#91]
![image](https://user-images.githubusercontent.com/11317404/84831463-03659b80-b034-11ea-9421-c1e1709eea83.png)

Looks like need add support of transform for Safari.

**Comment by evenstephenr** [comment]
@KozhokarAlex can you provide an example of the dataset and chart code here?

**Comment by tannerlinsley** [comment]
Due to a massive overhaul and rewrite of React Charts to TypeScript and a massively upgraded public API, this issue is being bulk closed for triage. The latest version can be tested via the `react-charts@beta` tag. Documentation is in the process of being upgraded, but thankfully, everything is fully typed now, so you can explore the API that way for now.

If, *after testing or playing with the v3 beta*, you believe your issue is still not addressed or relevant, feel free to open a new issue.
